from enum import Enum


class MLErrorCode(str, Enum):
    # Pipeline errors  1xxx
    PIPELINE_NOT_FOUND = "ML_1001"
    PIPELINE_ALREADY_RUNNING = "ML_1002"
    PIPELINE_FAILED = "ML_1003"
    CHUNK_BUFFER_OVERFLOW = "ML_1004"
    CHUNK_GAP_DETECTED = "ML_1005"
    ASSEMBLY_FAILED = "ML_1006"
    VERDICT_NOT_READY = "ML_1007"

    # Face errors  2xxx
    FACE_NOT_DETECTED = "FACE_2001"
    FACE_VALIDATION_FAILED = "FACE_2002"
    LIVENESS_CHECK_FAILED = "FACE_2003"
    DUPLICATE_CHECK_FAILED = "FACE_2004"
    EMBEDDING_EXTRACTION_FAILED = "FACE_2005"

    # Degree errors  3xxx
    DEGREE_OCR_FAILED = "DEGREE_3001"
    DEGREE_IMAGE_INVALID = "DEGREE_3002"

    # Interview scoring errors  4xxx
    SCORER_API_FAILED = "SCORE_4001"
    SCORER_INVALID_RESPONSE = "SCORE_4002"
    TRANSCRIPT_EMPTY = "SCORE_4003"

    # Storage errors  5xxx
    STORAGE_WRITE_FAILED = "STORE_5001"
    STORAGE_READ_FAILED = "STORE_5002"
    STORAGE_DELETE_FAILED = "STORE_5003"
    FILE_NOT_FOUND = "STORE_5004"

    # Kafka errors  6xxx
    KAFKA_CONSUMER_FAILED = "KAFKA_6001"
    KAFKA_MESSAGE_INVALID = "KAFKA_6002"

    # DB errors  7xxx
    DB_CONNECTION_FAILED = "DB_7001"
    DB_QUERY_FAILED = "DB_7002"
    DB_INTEGRITY_ERROR = "DB_7003"

    # Cache errors  8xxx
    REDIS_CONNECTION_FAILED = "CACHE_8001"
    REDIS_OPERATION_FAILED = "CACHE_8002"

    # Generic  9xxx
    INTERNAL_ERROR = "SRV_9001"
    VALIDATION_ERROR = "SRV_9002"
    NOT_FOUND = "SRV_9003"
